### ISSUE TITLE
File upload on old browsers crash

### ISSUE THREAD

**Issue by lpawlak** [NullDesk/TicketDesk#46] opened 2015-05-07 11:07 UTC
When I click Upload on old browser (IE9) I get following error:

> The parameters dictionary contains a null entry for parameter 'tempId' of non-nullable type 'System.Guid' for method 'System.Threading.Tasks.Task`1[System.Web.Mvc.ActionResult] Upload(System.Guid)' in 'Web.Controllers.FileController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter. Parameter name: parameters

**Comment by StephenRedd** [comment] 2015-05-12 15:39
Currently, the dropzone component powering file uploads has some issues (see issue #44). When we address that issue, we'll take a quick run at IE 9 to see what the problem is, and if trivial we'll address it. 

IE 9 is out of scope for TD 2.5 and higher. With luck, it will work on IE 9 when we get to final release, but the core development will not focus on compatibility with non-evergreen browsers. 

If IE 9 compatibility is important to the community, we will gladly accept pull requests for IE 9 issues so long as the compatibility does't undermine support for modern browsers.

**Closed** 2016-08-25 21:30 UTC
Labels: bug
