### ISSUE TITLE
Re-Open a force closed Ticket

### ISSUE THREAD

**Issue by razone-cl** [NullDesk/TicketDesk#133] opened 2017-02-28 15:44 UTC
Is it Possible?

**Comment by StephenRedd** [comment] 2017-03-01 00:41
Closed tickets can be re-opened. 

Force close differs from close only in who initiates the action. The standard workflow assumes the creator/owner closes the ticket. Force close is used by staff to closes an issue, rather having the owner do. They generate different activity messages, but the ticket's status is the same either way.

**Comment by razone-cl** [comment] 2017-03-01 11:49
First of all thankyou for the quick answer, Stephen, it looks like the button isn´t displaying at all, I leave as evidence that i changed the language of everything in spanish, including buttons, may that be the issue?

**Comment by StephenRedd** [comment] 2017-03-01 14:56
That seems odd. This TD 2.5 or 2.1?

**Comment by razone-cl** [comment] 2017-03-01 15:02
it's 2.1, any suggestions?

**Comment by StephenRedd** [comment] 2017-03-02 06:32
I'll need to dust off a copy and check into it for you.; it's been a while since I worked with it.

**Comment by StephenRedd** [comment] 2017-03-02 22:13
Ok, went back to re-familiarize myself with this feature in TD 2.1. There are no security checks controlling if or when the re-open button appears. As long as the ticket is resolved or closed, then there should be a re-open button. Force close doesn't do anything special other than close the ticket.

I can confirm that running the stock TD 2.1 code, closing, resolving, and force close all work as expected, and all result in displaying the re-open button.

**Comment by razone-cl** [comment] 2017-03-03 14:00
Well i must have messed up something when translating to spanish, and it's been so long since i've looked into this project that i dont really know where to look for it ahahah, but, thank you very much for your concern and and answers.

**Comment by StephenRedd** [comment] 2017-03-03 14:08
Take a look at this view:  https://github.com/NullDesk/TicketDesk/blob/ticketdesk-v2.1/TicketDesk-2/TicketDesk.Web.Client/Views/TicketEditor/Controls/ActivityButtons.ascx

If you messed something up in translation, the if statements that control each button in this view are the most likely place to start.

**Comment by razone-cl** [comment] 2017-03-03 14:44
So, I was checking what you told me and i found something disturbing xD, i have a dev project and the one already in production, both pointing to the same DB for this purpose, and i noticed that tickets that are **resolved** appear like this in production (wrong):
![ticket1](https://cloud.githubusercontent.com/assets/21272301/23555065/3e6f86e6-0006-11e7-8069-ed25a1b829d1.jpg)

and like this in my local project (right i guess):
![ticket2](https://cloud.githubusercontent.com/assets/21272301/23555109/63bf58fe-0006-11e7-9214-a384efa51dc1.jpg)


if you don't understand Spanish "Re-Abrir" stands for "Re open", the button i'm missing in production.


Maybe it isn't updating the ticket status correctly?

**Comment by StephenRedd** [comment] 2017-03-03 15:02
It certainly looks like production thinks that ticket is still active. I think it might depend on which application resolved the ticket. TD 2 was not designed for web farms at all, and each instance of the application tends to reuse ticket repository and EF contexts a lot; so you are probably just getting an the previously loaded ticket data, not fresh data from the DB.  You can confirm that by restarting production... it should then look just like your local when you go back to that ticket.

**Comment by razone-cl** [comment] 2017-03-03 15:34
What do you mean by restarting it? what is the impact that that may have on the data that's already there in production?

**Comment by StephenRedd** [comment] 2017-03-05 04:53
I mean to just restart the web site. It wont impact any data stored in the DB, just force TD to re-query for fresh data... it's effectively doing the same thing as a system that uses an in-memory cache, though the mechanics are a bit different.

**Comment by razone-cl** [comment] 2017-03-06 12:00
i've done that a few times before, when the site has crashed because of server issues, but i have never seen that that action brought up the missing button, i took a print of the settings table on SQL, maybe there's something wrong there, i also noticed that the version states as 2.0 there:

![ticketsetiings](https://cloud.githubusercontent.com/assets/21272301/23609097/268315e2-024b-11e7-99da-ff6b3082df1e.png)

**Comment by StephenRedd** [comment] 2017-03-07 04:06
That version flag looks correct to me. 

If you have two instances talking to the same DB, and one behaves differently from the other, it's very unlikely that the problem is the data, or the database. More probable that there is a runtime difference in state between the two running application instances, or the code itself isn't the same between the two instances.

**Closed** 2017-03-26 03:31 UTC
Labels: TD 2.1x
