### ISSUE TITLE
Internal Users Error when assigning ticket on create

### ISSUE THREAD

**Issue by jmbalanag** [NullDesk/TicketDesk#86] opened 2015-07-21 16:23 UTC
I am encountering an issue when creating tickets only when the Assigned To option has value. The ticket is created, but the person whom the ticket is assigned encounters an error when navigating to the /tickets link.

**Comment by StephenRedd** [comment] 2015-07-22 05:20
Can you elaborate on which link the assigned user is clicking when they get an exception?

I've put this through some testing with multiple users and types , and haven't found any case where navigating to ticket details (by link or direct URL) will throw an exception. 

I did find some issues with form permissions though, one being that internal users shouldn't ever see the assign to field on new ticket forms in the first place. I'll fix that, but I'd still like to know how to reproduce this exception in case it has a broader scope than just this one scenario.

**Comment by StephenRedd** [comment] 2015-07-22 05:51
references fixes for #87 and #88

**Comment by StephenRedd** [comment] 2016-01-10 05:19
I believe this may have been related to #99 considering that the exception was with the /tickets route, not the ticket/id route.

Unable to reproduce currently, please reopen if still an issue.

**Comment by StephenRedd** [comment] 2016-01-10 06:41
nevermind, reproduced. Debugging to see what the underlying cause is; seems related to #99, but is clearly not fixed by changes made for that issue.

**Closed** 2016-04-10 22:49 UTC
Labels: bug
