### ISSUE TITLE
UI Layout - Horizontal Scroll

### ISSUE THREAD

**Issue by AshleyMedway** [NullDesk/TicketDesk#79] opened 2015-06-26 06:55 UTC
I've noticed that in every browser I have tested the azure demo site in there is a horizontal scroll bar.
The scrollbar only disappears at smaller screen sizes.

**Comment by StephenRedd** [comment] 2015-06-26 12:56
This is caused by a container div in the navbar that has the class row applied. It will be fixed when I finish the changes for the project menu later today.

**Closed** 2015-06-27 07:32 UTC
Labels: bug
